# This file contains all the "targets" cross can be used with by default and is used for generating `src/docker/provided_images.rs` and our images
# the only required value for a `target` entry is its name in `target.target` and the `os` to use in CI
#
# spec is available in `xtask/src/util.rs` on `CiTarget`

[[target]]
target = "aarch64-unknown-linux-gnu"
os = "ubuntu-latest"
cpp = true
dylib = true
std = true
run = true
runners = "qemu-user qemu-system"
